#! /bin/sh


case "$1" in
start)
echo "Starting init script for I2C module"
modprobe i2c-dev
modprobe i2c-bcm2835
;;
stop)
echo "Removing user modules"
rmmod i2c-bcm2835
rmmod i2c-dev
;;
*)
echo "Usage: $0 {start|stop}"
exit 1
esac
exit 0
