#! /bin/sh

DAEMON=/opt/sensehatlive/sensehatlive.py
PIDFILE=/opt/sensehatlive/sensehatlive.pid

case "$1" in
	start)
		echo "Starting init script for I2C and SPI module"
		modprobe i2c-dev
		modprobe i2c-bcm2835
		modprobe spi-bcm2835  
		modprobe spidev  
		sleep 2
		start-stop-daemon -S -x "$DAEMON" -- -d --pidfile "$PIDFILE"
		;;
	stop)
		echo "Removing user modules"
		rmmod i2c-bcm2835
		rmmo i2c-dev
		rmmod spi-bcm2835  
		rmmo spidev  
		if [-e "$PIDFILE" ]
		then
			rm "$PIDFILE"
		fi
		;;
*)
	echo "Usage: $0 {start|stop}"
	exit 1

esac
exit 0
