#!/bin/sh
module=can

# Kernel version
KERNEL=`uname -r`
MODULE_DIR="/lib/modules/${KERNEL}/kernel/net/can"
DRIVER_MODULE_DIR="/lib/modules/${KERNEL}/kernel/drivers/net/can"

# Load protocol modules 
insmod ${MODULE_DIR}/${module}.ko || exit 1
insmod ${MODULE_DIR}/${module}-raw.ko || exit 1

# Load driver modules 
insmod ${DRIVER_MODULE_DIR}/${module}-dev.ko || exit 1
insmod ${DRIVER_MODULE_DIR}/c_can/c_${module}.ko || exit 1
insmod ${DRIVER_MODULE_DIR}/c_can/c_${module}_platform.ko || exit 1
